### ISSUE TITLE
Unknown at rule @tailwindcss(unknownAtRules)

### ISSUE THREAD

**Issue by R-Bhandari** [adrianhajdin/project_ai_summarizer#14]
I am getting this type of error when copying the App.css file from your repo.
And because of this I am not able to get any css in the output its just a blank white screen
![image](https://github.com/adrianhajdin/project_ai_summarizer/assets/99389888/1f7f8bc3-8141-41d3-99f4-c30b6ecf28b5)

**Comment by KChakhalyan** [comment]
Try
CTRL+SHIFT+P(macOs Command+Shift+P) which brings up the Command Palette. Then write "Change Language Mode" and then type "tailwind".. 
![Screenshot 2023-09-15 at 01 29 24](https://github.com/adrianhajdin/project_ai_summarizer/assets/10487372/f7c3707e-c290-4843-8c8b-69448da5e2f0)

select Tailwind CSS.. and enjoy. Let me know if it helps you.

**Comment by R-Bhandari** [comment]
Thanks it worked
